agent.omsr.mongo.enabled=true
agent.omsr.mongo.uri=mongodb://127.0.0.1:27017/ai_agent_config?replicaSet=rs0
agent.omsr.mongo.database=ai_agent_config
agent.omsr.mongo.collection=3p_rpa_config
agent.omsr.mongo.agent-id=omsr
agent.omsr.mongo.process-existing-on-startup=false
agent.omsr.mongo.mark-dispatched=true
agent.omsr.mongo.status-field=eventStatus
agent.omsr.mongo.event-store-enabled=true
agent.omsr.mongo.event-store-collection=3p_rpa_event_log
agent.omsr.mongo.processed-load-store-enabled=true
agent.omsr.mongo.processed-load-collection=3p_rpa_extracted_loads
agent.omsr.job.enabled=false
