<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.hwyhaul</groupId>
        <artifactId>itrade-load-creation-agent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>itrade-load-creation-agent-infrastructure</artifactId>
    <properties>
		<maven.deploy.skip>true</maven.deploy.skip>
	</properties>
    <dependencies>
        <dependency>
            <groupId>com.hwyhaul</groupId>
            <artifactId>common-spring-non-reactive-mongodb-shared-kernel</artifactId>
            <exclusions>
	            <exclusion>
					<groupId>com.querydsl</groupId>
					<artifactId>querydsl-mongodb</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.querydsl</groupId>
					<artifactId>querydsl-apt</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.javers</groupId>
					<artifactId>javers-spring-boot-starter-mongo</artifactId>
				</exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.hwyhaul</groupId>
            <artifactId>itrade-load-creation-agent-mcp-server</artifactId>
            <version>0.0.1-SNAPSHOT</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.ai</groupId>
                    <artifactId>spring-ai-starter-mcp-server</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.microsoft.playwright</groupId>
            <artifactId>playwright</artifactId>
            <version>1.44.0</version>
        </dependency>
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-open-ai</artifactId>
            <version>0.33.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>com.nickwongdev</groupId>
				<artifactId>aspectj-maven-plugin</artifactId>
				<configuration>
					<aspectLibraries>
						<aspectLibrary>
							<groupId>com.hwyhaul</groupId>
							<artifactId>iam-infrastructure-shared-kernel</artifactId>
						</aspectLibrary>
					</aspectLibraries>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
